FORMAT: 1A
HOST: https://spotifavorites.herokuapp.com

# Spotifav App

# Group Users
## Get users [GET api/users{?first}{?offset}{?term}]
+ Response 200 (application/json)
  + Attributes (array[User])
+ Response 403 (application/json)
+ Response 401 (application/json)

## Create a user [POST api/signup]
+ Body
  `{ email: "john.doe@mail.com", pwd: "azerty", confirmedPassword: "azerty" }`
+ Response 200 (application/json)

## Get connected user [GET api/users/profile]
+ Response 200 (application/json)
  + Attributes (array[User])
+ Response 404 (application/json)
+ Response 403 (application/json)
+ Response 401 (application/json)

## Delete connected user [DELETE api/users/deleteme]
+ Response 200 (application/json)
  + Attributes (User)
+ Response 404 (application/json)
+ Response 403 (application/json)
+ Response 401 (application/json)

## Update connected user [PATCH api/users/updateme]
+ Body
  `{ firstName: "john", lastName: "doe" }`
+ Response 200 (application/json)
  + Attributes (User)
+ Response 404 (application/json)
+ Response 403 (application/json)
+ Response 401 (application/json)

## Get token of a user [POST api/users/login]
+ Body
  `{ email: "john.doe@mail.com", password: "azerty" }`
+ Response 200 (application/json)
+ Response 404 (application/json)

## Manage a user for admin [/users/{userEmail}]
### Get a user [GET]
+ Response 200 (application/json)
  + Attributes (User)
+ Response 404 (application/json)
+ Response 403 (application/json)

### Update a user [PATCH /users/{userEmail}]
+ Body
  `{ email: "john.doe@mail.com", pwd: "azerty" }`
+ Response 200 (application/json)
  + Attributes (User)
+ Response 404 (application/json)
+ Response 403 (application/json)

### Delete a user [DELETE /users/{userEmail}]
+ Response 200 (application/json)
  + Attributes (User)
+ Response 404 (application/json)
+ Response 403 (application/json)

#Group Albums

## Get Albums [GET /albums]
+ Response 201 (application/json)
  + Attributes (array[Album])
+ Response 401 (application/json)

## Get favorites [GET /users/{userId}/favorites]
+ Response 200 (application/json)
  + Attributes (array[Album])
+ Response 404 (application/json)
+ Response 403 (application/json)

## Create a favorite [POST /users/{userId}/favorites]
+ Body
  `{ albumId: "3T4fUhGYeRNVUGevb0wThu" }`
+ Response 201 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)

## Get a favorite [GET /users/{userId}/favorites/{favoriteId}]
+ Response 200 (application/json)
  + Attributes (array[Album])
+ Response 401 (application/json)
+ Response 404 (application/json)
+ Response 403 (application/json)

## Delete a favorite [DELETE /users/{userId}/favorites/{favoriteId}]
+ Response 201 (application/json)
  + Attributes (array[Album])
+ Response 401 (application/json)
+ Response 404 (application/json)
+ Response 403 (application/json)

## Get all favorite for admin [GET /admin/favorites]
+ Response 201 (application/json)
  + Attributes (array[Album])
+ Response 404 (application/json)
+ Response 403 (application/json)

## Delete a favorite for admin [DELETE /admin/favorites/{favoriteId}]
+ Response 201 (application/json)
  + Attributes (array[Album])
+ Response 401 (application/json)
+ Response 404 (application/json)
+ Response 403 (application/json)


# Data Structures

## User (object)
+ firstName (string)
+ lastName (string)
+ isAdmin (boolean, required)
+ email (string, required)
+ password (string, required)

## Album (object)
+ albumName (string, required)
+ artistName (string, required)
+ year (string, required)
+ userId (string, required)
